
import { ArrowCircleRightIcon } from '@heroicons/react/solid';
import type { NextPage } from 'next'
import { getSession, signIn } from 'next-auth/react';
import Head from 'next/head';


 const Sign: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Twittos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-gray-700 ">
        <div className="flex min-h-screen items-center justify-center">
          <div className="min-h-1/2 bg-gray-900  border border-gray-900 rounded-2xl">
            <div className="sm:mx-24 md:mx-34 lg:mx-56 mx-auto flex items-center space-y-4 py-16 font-semibold text-gray-500 flex-col">
              <ArrowCircleRightIcon className=" h-12 w-12 text-white cursor-pointer" fill="currentColor" onClick={() => signIn()} />
              <h1 className="text-white text-2xl">Se connecter à Twittos</h1>
            </div>
          </div>
      {/*     <button className="hidden xl:inline ml-auto bg-[#1d9bf0] text-white rounded-full w-56 h-[52px] text-lg font-bold shadow-md hover:bg-[#1a8cd8]"
            onClick={() => signIn()}>
            Commencer
          </button> */}
        </div>
      </body>
    </div>

  )
}

export default Sign

export async function getServerSideProps(context: any) {
  const session = await getSession(context)
  if (session) {
    return {
      redirect: {
        destination: `/Home`,
        permanent: false
      },
    }
  }
  return {
    props: {},
  }
}
